# Generated by Django 5.1.1 on 2024-09-16 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_deleted',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='priority',
            old_name='is_deleted',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_deleted',
            new_name='is_active',
        ),
    ]
